steps:
  # Step 1: Build the container image with build-args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--network=host'
      - '-t'
      - 'gcr.io/$PROJECT_ID/votenavigator:$COMMIT_SHA'
      - '--build-arg'
      - 'NEXT_PUBLIC_GA_MEASUREMENT_ID=${_NEXT_PUBLIC_GA_MEASUREMENT_ID}'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/votenavigator:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'votenavigator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/votenavigator:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY},NEXT_PUBLIC_GA_MEASUREMENT_ID=${_NEXT_PUBLIC_GA_MEASUREMENT_ID}'

images:
  - 'gcr.io/$PROJECT_ID/votenavigator:$COMMIT_SHA'

timeout: '1200s'
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-west1'
